### ISSUE TITLE
static

### ISSUE THREAD

**Issue by robertgibbs2128** [nikivanov/mural#59]
is there anyway to make the home position static. mine is in a fixed place on my wall and has a paper roll that it draws on, if home position were static in the same location every time it would make it real easy to manually home mural to stay centered on my paper.

**Comment by nikivanov** [comment]
Home position is in the middle width-wise and 350mm from the top of the drawing area. So it's fixed in this regard. I'm not sure what's not working for you - please elaborate.

**Comment by robertgibbs2128** [comment]
I figured it out u was still getting some belt skip, and home seemed to be all over the place. I sometimes wish i was born smarter instead of so devistatingly handsome!

**Comment by nikivanov** [comment]
Def go with looks if you can!

One other user reported belts skipping and it was because his pulley was 16T not 20T. I'd verify that.
